language: node_js
node_js: node
addons:
  chrome: stable
before_install:
- npm config set @d2l:registry "${ARTIFACTORY_NPM_REGISTRY}"
- echo "$( echo ${ARTIFACTORY_NPM_REGISTRY} | sed 's/^http\(s\)\?://'):_authToken=${ARTIFACTORY_NPM_RO_TOKEN}" >> ~/.npmrc
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:local || travis_terminate 1;
  fi
- |
  if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == false ] && [ $TRAVIS_EVENT_TYPE != "cron" ]; then
    echo "Not a Pull Request and on branch master so bumping version";
    frauci-update-version;
    export TRAVIS_TAG=$(frauci-get-version)
  fi
env:
  global:
  - OWNER_NAME=Brightspace
  - REPO_NAME=d2l-note
  - SAUCE_USERNAME: Desire2Learn
  # SAUCE_ACCESS_KEY
  - secure: "C1l0A7+LjtW5WEb/EoHyad65piudeBFF+SuVGzsAHjCgPqg5bCiZCQMd0cownpGo4koYrMFIKFXe4NyXaeLZkYo+jWrfqJPg5HjEiBg7GY+JVksuLV52cY5fJIiTFNN+AFHvl3FJryAHIKcPQxp0J4LdAa0iYQYcPZl93+iE7WfSQL/B/d3EE8IqpFyaeS5Ovj33kUJLUx5LMzp73NeK63fZqsYm5l7fDY5tQBAG3anmJQL4T7QE9NrZaFvwd5P5bqlUUKLS1nRV0q+8T2Pdbd6SrY4Zl6QKOdqZR35dH4hWqqWd62VN2A/zTaOL9GiEaR6DzeB4+Sf28L3Co/Yv6XDUEXf8FVzhlJnhOq2HSu51e2mAyqxr1WQ90xQvScW9jNk5SI+sCebIM7CEpc7asvhgXlKHRDtRumiNBKvtDp8qSfm+lrB4CJianoKSSVuIS0INRU6QCC8C1Yg1Q4U9wQGcwOKFnfBtFQ5Fp7l08wdG3ThZQ/iKRsihYWyU0wHRbY9GcKDSPbCcYKKvCwcq9iWcgm3h7ucpa98V8WA2SFHDO0Hzr6Lg3Wwnrd8J1UQ86I4UlqMp+eeHoDP4tFSPg3G+Hy+79kEFHEV3bLbnlsEMflJeMp18IEmPg2SqBIUz7t5crFBKBjxPAv3p0/UBYmlw6K6kyC5r5mdQcd9bkrc="
